//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fuel.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fuel.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        public static string AppBarButtonRefresh {
            get {
                return ResourceManager.GetString("AppBarButtonRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sim.
        /// </summary>
        public static string AppBarButtonSim {
            get {
                return ResourceManager.GetString("AppBarButtonSim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usage.
        /// </summary>
        public static string AppBarButtonUsage {
            get {
                return ResourceManager.GetString("AppBarButtonUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AppBarMenuAbout {
            get {
                return ResourceManager.GetString("AppBarMenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to profile.
        /// </summary>
        public static string AppBarMenuProfile {
            get {
                return ResourceManager.GetString("AppBarMenuProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string AppBarMenuSettings {
            get {
                return ResourceManager.GetString("AppBarMenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sms balance.
        /// </summary>
        public static string AppBarMenuSmsBalance {
            get {
                return ResourceManager.GetString("AppBarMenuSmsBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sms topup.
        /// </summary>
        public static string AppBarMenuSmsTopup {
            get {
                return ResourceManager.GetString("AppBarMenuSmsTopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bonus.
        /// </summary>
        public static string MainViewBonus {
            get {
                return ResourceManager.GetString("MainViewBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bundle.
        /// </summary>
        public static string MainViewBundle {
            get {
                return ResourceManager.GetString("MainViewBundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to free data.
        /// </summary>
        public static string MainViewFreeData {
            get {
                return ResourceManager.GetString("MainViewFreeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to free sms.
        /// </summary>
        public static string MainViewFreeSms {
            get {
                return ResourceManager.GetString("MainViewFreeSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left.
        /// </summary>
        public static string MainViewLeft {
            get {
                return ResourceManager.GetString("MainViewLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to viking call.
        /// </summary>
        public static string MainViewVikingCall {
            get {
                return ResourceManager.GetString("MainViewVikingCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to viking SMS.
        /// </summary>
        public static string MainViewVikingSms {
            get {
                return ResourceManager.GetString("MainViewVikingSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fetching data.
        /// </summary>
        public static string ProgressfecthingData {
            get {
                return ResourceManager.GetString("ProgressfecthingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading sims.
        /// </summary>
        public static string ProgressLoadingSims {
            get {
                return ResourceManager.GetString("ProgressLoadingSims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bummer, it looks like we&apos;re all out of internet.
        /// </summary>
        public static string ToastBummer {
            get {
                return ResourceManager.GetString("ToastBummer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to default sim does not exist anymore, loading first.
        /// </summary>
        public static string ToastDefaultSim {
            get {
                return ResourceManager.GetString("ToastDefaultSim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hold your horses, we still need to load some information here.
        /// </summary>
        public static string ToastHoldHorses {
            get {
                return ResourceManager.GetString("ToastHoldHorses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to there is no sim linked to this account.
        /// </summary>
        public static string ToastNoSim {
            get {
                return ResourceManager.GetString("ToastNoSim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please wait till your sim information is loaded.
        /// </summary>
        public static string ToastSimLoaded {
            get {
                return ResourceManager.GetString("ToastSimLoaded", resourceCulture);
            }
        }
    }
}
