//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fuel.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fuel.Localization.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to calendar.
        /// </summary>
        public static string AppBarButtonCalendar {
            get {
                return ResourceManager.GetString("AppBarButtonCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string AppBarButtonCancel {
            get {
                return ResourceManager.GetString("AppBarButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next.
        /// </summary>
        public static string AppBarButtonNext {
            get {
                return ResourceManager.GetString("AppBarButtonNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ok.
        /// </summary>
        public static string AppBarButtonOk {
            get {
                return ResourceManager.GetString("AppBarButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        public static string AppBarButtonRefresh {
            get {
                return ResourceManager.GetString("AppBarButtonRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sim.
        /// </summary>
        public static string AppBarButtonSim {
            get {
                return ResourceManager.GetString("AppBarButtonSim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usage.
        /// </summary>
        public static string AppBarButtonUsage {
            get {
                return ResourceManager.GetString("AppBarButtonUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AppBarMenuAbout {
            get {
                return ResourceManager.GetString("AppBarMenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last day.
        /// </summary>
        public static string AppBarMenuLastDay {
            get {
                return ResourceManager.GetString("AppBarMenuLastDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last month.
        /// </summary>
        public static string AppBarMenuLastMonth {
            get {
                return ResourceManager.GetString("AppBarMenuLastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last week.
        /// </summary>
        public static string AppBarMenuLastWeek {
            get {
                return ResourceManager.GetString("AppBarMenuLastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to profile.
        /// </summary>
        public static string AppBarMenuProfile {
            get {
                return ResourceManager.GetString("AppBarMenuProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string AppBarMenuSettings {
            get {
                return ResourceManager.GetString("AppBarMenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sms balance.
        /// </summary>
        public static string AppBarMenuSmsBalance {
            get {
                return ResourceManager.GetString("AppBarMenuSmsBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sms topup.
        /// </summary>
        public static string AppBarMenuSmsTopup {
            get {
                return ResourceManager.GetString("AppBarMenuSmsTopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usage.
        /// </summary>
        public static string DetailsViewSubtitleDefault {
            get {
                return ResourceManager.GetString("DetailsViewSubtitleDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from.
        /// </summary>
        public static string DetailsViewSubtitleFrom {
            get {
                return ResourceManager.GetString("DetailsViewSubtitleFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to until.
        /// </summary>
        public static string DetailsViewSubtitleUntil {
            get {
                return ResourceManager.GetString("DetailsViewSubtitleUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usage.
        /// </summary>
        public static string DetailsViewUsage {
            get {
                return ResourceManager.GetString("DetailsViewUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        public static string LoginPassword {
            get {
                return ResourceManager.GetString("LoginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sign in.
        /// </summary>
        public static string LoginSignIn {
            get {
                return ResourceManager.GetString("LoginSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username or password.
        /// </summary>
        public static string LoginUserName {
            get {
                return ResourceManager.GetString("LoginUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bonus.
        /// </summary>
        public static string MainViewBonus {
            get {
                return ResourceManager.GetString("MainViewBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bundle.
        /// </summary>
        public static string MainViewBundle {
            get {
                return ResourceManager.GetString("MainViewBundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to free data.
        /// </summary>
        public static string MainViewFreeData {
            get {
                return ResourceManager.GetString("MainViewFreeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to free sms.
        /// </summary>
        public static string MainViewFreeSms {
            get {
                return ResourceManager.GetString("MainViewFreeSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left.
        /// </summary>
        public static string MainViewLeft {
            get {
                return ResourceManager.GetString("MainViewLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to viking call.
        /// </summary>
        public static string MainViewVikingCall {
            get {
                return ResourceManager.GetString("MainViewVikingCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to viking SMS.
        /// </summary>
        public static string MainViewVikingSms {
            get {
                return ResourceManager.GetString("MainViewVikingSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your credentials are not stored locally and will only be used to request a token.
        /// </summary>
        public static string PopupPrivacy {
            get {
                return ResourceManager.GetString("PopupPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to privacy notice.
        /// </summary>
        public static string PopupPrivacyHeader {
            get {
                return ResourceManager.GetString("PopupPrivacyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to earned.
        /// </summary>
        public static string ProfileViewEarned {
            get {
                return ResourceManager.GetString("ProfileViewEarned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to points
        ///points.
        /// </summary>
        public static string ProfileViewPoints {
            get {
                return ResourceManager.GetString("ProfileViewPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to referrals.
        /// </summary>
        public static string ProfileViewReferral {
            get {
                return ResourceManager.GetString("ProfileViewReferral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remaining.
        /// </summary>
        public static string ProfileViewRemaining {
            get {
                return ResourceManager.GetString("ProfileViewRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join the revolution, become a viking! #fuel.
        /// </summary>
        public static string ProfileViewShareLinkBody {
            get {
                return ResourceManager.GetString("ProfileViewShareLinkBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Become a viking!.
        /// </summary>
        public static string ProfileViewShareLinkTitle {
            get {
                return ResourceManager.GetString("ProfileViewShareLinkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to topups used.
        /// </summary>
        public static string ProfileViewTopupsUsed {
            get {
                return ResourceManager.GetString("ProfileViewTopupsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to used.
        /// </summary>
        public static string ProfileViewUsed {
            get {
                return ResourceManager.GetString("ProfileViewUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to waiting.
        /// </summary>
        public static string ProfileViewWaiting {
            get {
                return ResourceManager.GetString("ProfileViewWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fetching data.
        /// </summary>
        public static string ProgressFetchingData {
            get {
                return ResourceManager.GetString("ProgressFetchingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fetching links.
        /// </summary>
        public static string ProgressFetchingLinks {
            get {
                return ResourceManager.GetString("ProgressFetchingLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getting statistics.
        /// </summary>
        public static string ProgressGettingStatistics {
            get {
                return ResourceManager.GetString("ProgressGettingStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading sims.
        /// </summary>
        public static string ProgressLoadingSims {
            get {
                return ResourceManager.GetString("ProgressLoadingSims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to requesting access.
        /// </summary>
        public static string ProgressRequestingAccess {
            get {
                return ResourceManager.GetString("ProgressRequestingAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getting card info.
        /// </summary>
        public static string ProgressRetrievingCardInfo {
            get {
                return ResourceManager.GetString("ProgressRetrievingCardInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getting price plan info.
        /// </summary>
        public static string ProgressRetrievingPricePlanInfo {
            get {
                return ResourceManager.GetString("ProgressRetrievingPricePlanInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to retrieving referrals.
        /// </summary>
        public static string ProgressRetrievingReferrals {
            get {
                return ResourceManager.GetString("ProgressRetrievingReferrals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to retrieving topups.
        /// </summary>
        public static string ProgressRetrievingTopups {
            get {
                return ResourceManager.GetString("ProgressRetrievingTopups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to retrieving information.
        /// </summary>
        public static string ProgressRetrievingUsage {
            get {
                return ResourceManager.GetString("ProgressRetrievingUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to card number.
        /// </summary>
        public static string SimViewCardNumber {
            get {
                return ResourceManager.GetString("SimViewCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imsi.
        /// </summary>
        public static string SimViewImsi {
            get {
                return ResourceManager.GetString("SimViewImsi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info.
        /// </summary>
        public static string SimViewInfo {
            get {
                return ResourceManager.GetString("SimViewInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pin 1.
        /// </summary>
        public static string SimViewPin1 {
            get {
                return ResourceManager.GetString("SimViewPin1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pin2.
        /// </summary>
        public static string SimViewPin2 {
            get {
                return ResourceManager.GetString("SimViewPin2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plan.
        /// </summary>
        public static string SimViewPlan {
            get {
                return ResourceManager.GetString("SimViewPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bundle.
        /// </summary>
        public static string SimViewPlanBundle {
            get {
                return ResourceManager.GetString("SimViewPlanBundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to prices.
        /// </summary>
        public static string SimViewPlanPrices {
            get {
                return ResourceManager.GetString("SimViewPlanPrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to puk 1.
        /// </summary>
        public static string SimViewPuk1 {
            get {
                return ResourceManager.GetString("SimViewPuk1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to puk 2.
        /// </summary>
        public static string SimViewPuk2 {
            get {
                return ResourceManager.GetString("SimViewPuk2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to topups.
        /// </summary>
        public static string SimViewTopups {
            get {
                return ResourceManager.GetString("SimViewTopups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to default sim does not exist anymore, loading first.
        /// </summary>
        public static string ToastDefaultSim {
            get {
                return ResourceManager.GetString("ToastDefaultSim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hey now, Marty McFly, let&apos;s stick to the present!.
        /// </summary>
        public static string ToastFutureDate {
            get {
                return ResourceManager.GetString("ToastFutureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hold your horses, we still need to load some information here.
        /// </summary>
        public static string ToastHoldHorses {
            get {
                return ResourceManager.GetString("ToastHoldHorses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please select a date later than the first one.
        /// </summary>
        public static string ToastInconsistentDateChoice {
            get {
                return ResourceManager.GetString("ToastInconsistentDateChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to looks like that&apos;s not a valid date, check again professor!.
        /// </summary>
        public static string ToastInvalidDate {
            get {
                return ResourceManager.GetString("ToastInvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login unsuccessful, please try again.
        /// </summary>
        public static string ToastLoginUnsuccessful {
            get {
                return ResourceManager.GetString("ToastLoginUnsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to there is no data for this period.
        /// </summary>
        public static string ToastNoDataForPeriod {
            get {
                return ResourceManager.GetString("ToastNoDataForPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bummer, it looks like we&apos;re all out of internet.
        /// </summary>
        public static string ToastNoInternet {
            get {
                return ResourceManager.GetString("ToastNoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to there is no sim linked to this account.
        /// </summary>
        public static string ToastNoSim {
            get {
                return ResourceManager.GetString("ToastNoSim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please provide a password.
        /// </summary>
        public static string ToastPassword {
            get {
                return ResourceManager.GetString("ToastPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please wait till your sim information is loaded.
        /// </summary>
        public static string ToastSimLoaded {
            get {
                return ResourceManager.GetString("ToastSimLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please provide a username.
        /// </summary>
        public static string ToastUserName {
            get {
                return ResourceManager.GetString("ToastUserName", resourceCulture);
            }
        }
    }
}
